// Development Service Worker for SIGO.
// Provides safe, non-throwing lifecycle during local development (`flutter run -d chrome`).
// The immutable offline release worker with atomic caching is generated by `python3 tool/prepare_pwa.py`.

self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Pass-through fetch in development to allow hot reload and fresh asset delivery
self.addEventListener('fetch', (event) => {
  return;
});
